---
output: pdf_document
params:
    title: "Disease Surveillance Report"
    report_year: 2025
    report_month: 1
    trend_threshold: 0.15
    report_data: NULL
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
---

<!-- general_report.Rmd is a template R Markdown document used for generating PDF reports of disease statistics -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r table, message=FALSE, warning=FALSE, results='asis'}
library(kableExtra)

r_data <- params$report_data

r_year <- params$report_year
r_month <- params$report_month
r_month_name <- month.name[r_month]

r_threshold <- params$trend_threshold
# Set threshold to default, if out of bounds
if (r_threshold < 0 | r_threshold > 1) {
    r_threshold <- 0.15
}

if (length(names(r_data)) == 8) {
    # Set header row from input parameters
    # This workaround is needed to dynamically create the header names
    header_2 <- c(3, 4)
    names(header_2) <- c(
        paste(r_month_name, r_year),
        paste0(r_year, " YTD", footnote_marker_symbol(4, double_escape = TRUE))
    )
    header_2 <- c(" ", header_2)

    # Build the table
    kbl(
        r_data,
        col.names = c(
            "Disease",
            paste0("Cases", footnote_marker_symbol(1)),
            paste0("Avg", footnote_marker_symbol(3)),
            paste0("Trend", footnote_marker_symbol(5)),
            paste0("Cases", footnote_marker_symbol(1)),
            paste0("Avg", footnote_marker_symbol(3)),
            paste0("Rate", footnote_marker_symbol(2)),
            paste0("Avg", footnote_marker_symbol(3))
        ),
        booktabs = TRUE,
        align = "lcclcccc",
        escape = FALSE
        ) |>
        add_header_above(header_2, escape = FALSE) |>
        kable_styling(
            latex_options = c("scale_down")
        ) |>
        column_spec(
            4,
            background = ifelse(
                r_data$Trend == "Elevated", "red",
                ifelse(r_data$Trend == "Expected", "yellow",
                "green"))
        ) |>
        footnote(symbol = c(
            "Number of reported cases",
            "Cases per 100,000 people",
            "5-year average. Averages are susceptible to skewing due to outbreaks and should be interpreted with care.",
            "Year-to-Date",
            paste0(
                "A percent change of ",
                r_threshold * 100,
                "% or more will result in a change in the trend"
            )
            ))
} else if (length(names(r_data)) == 4) {
    kbl(
        r_data,
        col.names = c(
            "Disease",
            paste0("Rate", footnote_marker_symbol(1)),
            paste0("Avg", footnote_marker_symbol(2)),
            paste0("Trend", footnote_marker_symbol(3))
        ),
        booktabs = TRUE,
        align = "lccl",
        escape = FALSE
        ) |>
        kable_styling(
            latex_options = c("scale_down")
        ) |>
        column_spec(
            4,
            background = ifelse(
                r_data$Trend == "Elevated", "red",
                ifelse(r_data$Trend == "Expected", "yellow",
                "green"))
        ) |>
        footnote(symbol = c(
            "Number of reported cases per 100,000 people",
            "5-year average",
            paste0(
                "A percent change of ",
                r_threshold * 100,
                "% or more will result in a change in the trend"
            )
            ))
}

```
